package entity;
// Generated 26/11/2019 01:16:58 PM by Hibernate Tools 4.3.1



/**
 * DetalleId generated by hbm2java
 */
public class DetalleId  implements java.io.Serializable {


     private long ventaid;
     private int cantidad;

    public DetalleId() {
    }

    public DetalleId(long ventaid, int cantidad) {
       this.ventaid = ventaid;
       this.cantidad = cantidad;
    }
   
    public long getVentaid() {
        return this.ventaid;
    }
    
    public void setVentaid(long ventaid) {
        this.ventaid = ventaid;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleId) ) return false;
		 DetalleId castOther = ( DetalleId ) other; 
         
		 return (this.getVentaid()==castOther.getVentaid())
 && (this.getCantidad()==castOther.getCantidad());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getVentaid();
         result = 37 * result + this.getCantidad();
         return result;
   }   


}


