package entity;
// Generated 26/11/2019 01:16:58 PM by Hibernate Tools 4.3.1



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private DetalleId id;
     private Producto producto;
     private Venta venta;

    public Detalle() {
    }

    public Detalle(DetalleId id, Producto producto, Venta venta) {
       this.id = id;
       this.producto = producto;
       this.venta = venta;
    }
   
    public DetalleId getId() {
        return this.id;
    }
    
    public void setId(DetalleId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


