package entity;
// Generated 26/11/2019 01:16:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private long idventa;
     private Date hora;
     private BigDecimal total;
     private long usuarioid;
     private Set detalles = new HashSet(0);

    public Venta() {
    }

	
    public Venta(long idventa, Date hora, BigDecimal total, long usuarioid) {
        this.idventa = idventa;
        this.hora = hora;
        this.total = total;
        this.usuarioid = usuarioid;
    }
    public Venta(long idventa, Date hora, BigDecimal total, long usuarioid, Set detalles) {
       this.idventa = idventa;
       this.hora = hora;
       this.total = total;
       this.usuarioid = usuarioid;
       this.detalles = detalles;
    }
   
    public long getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(long idventa) {
        this.idventa = idventa;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public long getUsuarioid() {
        return this.usuarioid;
    }
    
    public void setUsuarioid(long usuarioid) {
        this.usuarioid = usuarioid;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


